# A rough introduction to Python

Python files end in .py.
You can run files from the command line using the "python" command:
    python example.py
    
You can also open a python interpreter using a bare python command:
    python
    
Additionally, you can run python code on the command line or in bash/batch scripts using the -c flag:
    python -c "print 'Hello world'"

Python programs have the following components:

## Import statements

In [1]:
from __future__ import print_function

import numpy as np
import matplotlib.pyplot as plt

import scipy

from math import *

The first lines of any python program are the import statements. These let you load packages that you have installed to extend the functionality of Python.

There are multiple ways to import packages; best practice is to import packages as a short identifier (e.g. numpy as np).

To look up what's available in a package, Google is your friend; alternatively, you can use the dir command:

In [14]:
import numpy as np

print(dir(np)[0:20])
#This command cuts off the list of commands... there are a lot!

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf']


If you need help with a specific function, you can use the help command:

In [3]:
import numpy as np

help(np.savetxt)

Help on function savetxt in module numpy.lib.npyio:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
            a) a single specifier, `fmt='%.4e'`, resulting in numbers formatted
               like `' (%s+%sj)' % (fmt, fmt)`
            b) a full string specifying every real and imaginary part, e.g.
               `' %.

## variables

In [4]:
from __future__ import print_function

x = 1.0
print(type(x))

y = 1
print(type(y))

print(type(x-y))

print(type(1/2))
print(1/2)
print(1./2.)

<type 'float'>
<type 'int'>
<type 'float'>
<type 'int'>
0
0.5


## operators

Arithmetic: +, -, \*, /, //, \*\*

Comparison: >, <, ==, !=, >=, <=

Logic: and, or, not

## Lists (and numpy arrays)

Lists are python's built-in data structure. Elements of a list can be of multiple types (including objects and other lists!):

In [5]:
a = [1,2.0,3.0+1.0j]

for element in a:
    print(element)
    print(type(element))
    print('\n')

b = ['Hello',True, [a]]

for element in b:
    print(element)
    print(type(element))
    print('\n')

1
<type 'int'>


2.0
<type 'float'>


(3+1j)
<type 'complex'>


Hello
<type 'str'>


True
<type 'bool'>


[[1, 2.0, (3+1j)]]
<type 'list'>




Indexing for lists starts at 0!

In [6]:
a = [1, 2, 3, 4, 5]
print(a[0])
print(a[1])

1
2


Negative indices can be used to travel from the end of the list backwards:

In [7]:
a = [1,2,3,4,5]
print(a[-1])
print(a[-2])

5
4


The "range" command is super important. This is often what you will iterate over in a python for-loop.

Ranges start at the "start" argument, step by the "step" argument, and end on the condition i<stop:

In [8]:
start = 1
stop = 34
step = 3

print(range(start,stop,step))

[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31]


Lists can also be modified using some built-in methods:

In [15]:
a = []
print(a)

a.append(1.0)
a.append(2.0)
print(a)

a.insert(0,9.0)
print(a)

a[0] = 1.0
print(a)

del a[0]
print(a)



[]
[1.0, 2.0]
[9.0, 1.0, 2.0]
[1.0, 1.0, 2.0]
[1.0, 2.0]


Numpy arrays are similar to lists but can be only singly typed:

In [10]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<type 'numpy.ndarray'>


Numpy arrays can be used as arguments to numpy functions.

In [11]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.log(a)
print(b)

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


Cool trick with numpy arrays: logical indexing! This can be used to delete zero-valued elements from an array and more. A numpy array put through a comparator will output a boolean array that can be used as a mask to, e.g., screen out particular values from that array or another.

In [12]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5])
print(a>0)
print(a[a<3])
print(a[a!=0])

[False  True  True  True  True  True]
[0 1 2]
[1 2 3 4 5]


## control (if/else, for, while, try/except, ...)

## functions and classes

## Some I/O (using numpy)

In [18]:
import numpy as np
help(np.loadtxt))
help(np.genfromtxt())
help(np.savetxt())

Help on function loadtxt in module numpy.lib.npyio:

loadtxt(fname, dtype=<type 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes')
    Load data from a text file.
    
    Each row in the text file must have the same number of values.
    
    Parameters
    ----------
    fname : file, str, or pathlib.Path
        File, filename, or generator to read.  If the filename extension is
        ``.gz`` or ``.bz2``, the file is first decompressed. Note that
        generators should return byte strings for Python 3k.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type.
    comments : str or sequence of str, optional
        

TypeError: genfromtxt() takes at least 1 argument (0 given)